// This file is autogenerated by build-prefixes.js. DO NOT EDIT!

export interface Targets {
  android: string,
  chrome: string,
  edge: string,
  firefox: string,
  ie: string,
  ios_saf: string,
  opera: string,
  safari: string,
  samsung: string
}
