// This file is autogenerated by build-prefixes.js. DO NOT EDIT!

use crate::properties::prefixes::Browsers;

pub enum Feature {
  CssAnyLink,
  CssAutofill,
  CssCaseInsensitive,
  CssDefaultPseudo,
  CssDirPseudo,
  CssFirstLetter,
  CssFirstLine,
  CssFocusVisible,
  CssFocusWithin,
  CssGencontent,
  CssInOutOfRange,
  CssIndeterminatePseudo,
  CssMarkerPseudo,
  CssMatchesPseudo,
  CssNamespaces,
  CssOptionalPseudo,
  CssPlaceholder,
  CssPlaceholderShown,
  CssReadOnlyWrite,
  CssSel2,
  CssSel3,
  CssSelection,
  Dialog,
  FormValidation,
  Fullscreen,
  Shadowdomv1
}

impl Feature {
  pub fn is_compatible(&self, browsers: Browsers) -> bool {
    match self {
      Feature::CssSel2 => {
        if let Some(version) = browsers.ie {
          if version < 458752 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 131072 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 196864 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 197120 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 131328 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssSel3 => {
        if let Some(version) = browsers.ie {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 197888 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 197120 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 591104 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 197120 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 131328 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssGencontent => {
        if let Some(version) = browsers.ie {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 131072 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 196864 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 197120 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 131328 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssFirstLetter => {
        if let Some(version) = browsers.ie {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 197888 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 327936 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 722432 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 327680 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 196608 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssFirstLine => {
        if let Some(version) = browsers.ie {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 131072 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 196864 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 197120 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 131328 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssInOutOfRange => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3276800 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3473408 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655616 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 2621440 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 656128 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 327680 {
            return false
          }
        }
      }
      Feature::FormValidation => {
        if let Some(version) = browsers.ie {
          if version < 655360 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 655360 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655616 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 655360 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 656128 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 263171 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssAnyLink => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3276800 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 4259840 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 3407872 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 590336 {
            return false
          }
        }
      }
      Feature::CssDefaultPseudo => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3342336 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655616 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 2490368 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 656128 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 327680 {
            return false
          }
        }
      }
      Feature::CssDirPseudo => {
        if let Some(version) = browsers.firefox {
          if version < 3211264 {
            return false
          }
        }
      }
      Feature::CssFocusWithin => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3407872 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3932160 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655616 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 3080192 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 656128 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 524800 {
            return false
          }
        }
      }
      Feature::CssFocusVisible => {
        if let Some(version) = browsers.edge {
          if version < 5636096 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 5570560 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 5636096 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 4718592 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 917504 {
            return false
          }
        }
      }
      Feature::CssIndeterminatePseudo => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3342336 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 2555904 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655616 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 1703936 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 656128 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssMatchesPseudo => {
        if let Some(version) = browsers.edge {
          if version < 5767168 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 5111808 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 5767168 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 917504 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 4915200 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 917504 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 983040 {
            return false
          }
        }
      }
      Feature::CssOptionalPseudo => {
        if let Some(version) = browsers.ie {
          if version < 655360 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 983040 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 327680 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 983040 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 327680 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 131840 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssPlaceholderShown => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3342336 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3080192 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 2228224 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 327680 {
            return false
          }
        }
      }
      Feature::Dialog => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 2424832 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 1572864 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::Fullscreen => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 4194304 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 4653056 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 786688 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 655616 {
            return false
          }
        }
      }
      Feature::CssMarkerPseudo => {
        if let Some(version) = browsers.edge {
          if version < 5636096 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 4456448 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 5636096 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 4718592 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 721664 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 917504 {
            return false
          }
        }
      }
      Feature::CssPlaceholder => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3342336 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3735552 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655616 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 2883584 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 656128 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 459264 {
            return false
          }
        }
      }
      Feature::CssSelection => {
        if let Some(version) = browsers.ie {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 4063232 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 196864 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 591104 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 263168 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssCaseInsensitive => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 3080192 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3211264 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 2359296 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 327680 {
            return false
          }
        }
      }
      Feature::CssReadOnlyWrite => {
        if let Some(version) = browsers.edge {
          if version < 851968 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 5111808 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 2359296 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 1507328 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::CssAutofill => {
        if let Some(version) = browsers.chrome {
          if version < 6291456 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 6291456 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 5636096 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 5373952 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6291456 {
            return false
          }
        }
      }
      Feature::CssNamespaces => {
        if let Some(version) = browsers.ie {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.edge {
          if version < 786432 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 131072 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 262144 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 589824 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 262656 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 131328 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 262144 {
            return false
          }
        }
      }
      Feature::Shadowdomv1 => {
        if let Some(version) = browsers.edge {
          if version < 5177344 {
            return false
          }
        }
        if let Some(version) = browsers.firefox {
          if version < 4128768 {
            return false
          }
        }
        if let Some(version) = browsers.chrome {
          if version < 3473408 {
            return false
          }
        }
        if let Some(version) = browsers.safari {
          if version < 655360 {
            return false
          }
        }
        if let Some(version) = browsers.opera {
          if version < 2621440 {
            return false
          }
        }
        if let Some(version) = browsers.ios_saf {
          if version < 720896 {
            return false
          }
        }
        if let Some(version) = browsers.android {
          if version < 6160384 {
            return false
          }
        }
        if let Some(version) = browsers.samsung {
          if version < 393728 {
            return false
          }
        }
      }
    }
    true
  }
}
