name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      # clippy warn too much, temporary disable
      # - run: cargo clippy --all-targets
      - run: cargo test --all-features

  test-js:
    name: test-js (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1.8.32
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: yarn build
      - run: yarn test
      - run: yarn tsc

  test-wasm:
    name: test-wasm (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1.8.32
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install wasm-opt
        uses: phi-ag/setup-binaryen@v1
        with:
          version: "111"
      - name: Build wasm
        run: yarn wasm:build-release
      - run: yarn test
        env:
          TEST_WASM: node
      - run: yarn test
        env:
          TEST_WASM: browser
